### ISSUE TITLE
veams-cli throw e

### ISSUE THREAD

**Issue by sumnermic** [Sebastian-Fitzner/Veams#5]
Hello,

I happen to always receive the following error that I couldn't veam a new project:

Windows 10
npm 3.8.8
node 4.4.2
generator-veams: 6.7.3
veams-cli: 1.2.20
inserter: 1.0.4
yo 1.7.0

``C:\Users\user\AppData\Roaming\npm\node_modules\veams-cli\node_modules\yeoman-environment\node_modules\rx\dist\rx.js:77
    throw e;
    ^
 true``

Kind regards,

**Comment by Sebastian-Fitzner** [comment]
This issue is solved in the latest version.
